language: rust
sudo: false
dist: trusty
cache: cargo

rust:
  - stable

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e500fab33f96c33cc99
    on_success: change
    on_failure: always
    on_start: false


addons:
  apt:
    packages:
      - librdkafka1
      - librdkafka-dev
      - libssl-dev
      - libsasl2-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

script:
  - eval cargo build --verbose
  - eval cargo test --verbose
