language: rust
sudo: true
dist: trusty
cache: cargo

rust:
  - stable

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e500fab33f96c33cc99
    on_success: change
    on_failure: always
    on_start: false


addons:
  apt:
    packages:
      - libssl-dev
      - libsasl2-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_install:
  - wget https://github.com/edenhill/librdkafka/archive/v0.11.3.tar.gz
  - tar -xvf v0.11.3.tar.gz
  - cd librdkafka-0.11.3
  - ./configure
  - make
  - make install
  - cd ..

script:
  - eval cargo build --verbose
  - eval cargo test --verbose
